### ISSUE TITLE
Cannot connect with Metamask

### ISSUE THREAD

**Issue by Zilvin4s** [communa/frontend#1]
Connecting with Metamask throws such error

![Screenshot from 2023-06-26 16-08-36](https://github.com/communa/frontend/assets/9867718/247f009d-f066-4499-ba18-34d1539b27c2)

Additionally, api fails for `POST /api/auth/nonce` - API not created?

**Comment by ivanproskuryakov** [comment]
@Zilvin4s thanks for reporting on this

**Comment by ivanproskuryakov** [comment]
@Zilvin4s resolved, there was a deployment error.
